import io
import textwrap

import tomli_w

from rom_analyzer.emit_ld import (
    emit_crc_region_toml,
    emit_description_ld,
    emit_flash_free_toml,
    emit_omni_stub,
    emit_ram_free_toml,
)
from rom_analyzer.types import (
    CrcRegion,
    FlashFreeBlock,
    PropagatedSymbol,
    RamFreeBlock,
)


def test_emit_description_ld_groups_by_category():
    symbols = [
        PropagatedSymbol("flash_fuel_map_rpm_axis", 0xb2fa, 0xb2fa, "data", "high"),
        PropagatedSymbol("adc_run", 0x1533c, 0x1533c, "function", "high"),
        PropagatedSymbol("engine_rpm", 0x804e5c, 0x804e5c, "ram_global", "high"),
    ]
    out = emit_description_ld(symbols, source_rom="tiny.bin",
                              reference_name="33520003", variant="m32r:2:fp8000",
                              match_summary="1/1 (100%)")
    assert "/* Generated by rom-analyzer" in out
    # All three categories present, sorted by address within category
    assert "flash_fuel_map_rpm_axis = 0xb2fa;" in out
    assert "engine_rpm = 0x804e5c;" in out
    assert "adc_run = 0x1533c;" in out
    # Section headers
    assert "/* Flash table addresses */" in out
    assert "/* RAM globals */" in out
    assert "/* Function entry points */" in out


def test_emit_crc_region_toml():
    region = CrcRegion(0x0, 0x80000, 0x10000, 0x80000)
    out = emit_crc_region_toml(region)
    assert "[full_flash]" in out and "start = 0" in out and "end = 524288" in out
    assert "[partial_flash]" in out


def test_emit_flash_free_toml():
    blocks = [
        FlashFreeBlock("unprotected", 0x80000, 0x80100, 256),
        FlashFreeBlock("partial_crc", 0xb000, 0xb100, 256),
    ]
    out = emit_flash_free_toml(blocks)
    assert "band = \"unprotected\"" in out
    assert "band = \"partial_crc\"" in out


def test_emit_ram_free_toml():
    blocks = [
        RamFreeBlock(0x805f80, 0x805fa0, 32, ""),
        RamFreeBlock(0x80a000, 0x80b000, 4096, "suspicious_large_gap"),
    ]
    out = emit_ram_free_toml(blocks)
    assert "note = \"\"" in out
    assert "suspicious_large_gap" in out


def test_emit_omni_stub_auto_fills_when_one_unambiguous_unprotected():
    flash_blocks = [
        FlashFreeBlock("unprotected", 0x4f9a8, 0x4fa00, 88),
        FlashFreeBlock("unprotected", 0x90000, 0x90200, 512),
    ]
    # Largest unprotected is 0x90000 (512 bytes, > 2× the 88-byte block) — used to auto-fill
    ram_symbols = [
        PropagatedSymbol("calculated_gear", 0x805088, 0x805088, "ram_global", "high"),
    ]
    out = emit_omni_stub(flash_blocks, ram_symbols)
    assert "free_space_start = 0x90000;" in out
    assert "free_space_end   = 0x90200;" in out
    assert "calculated_gear = 0x805088;" in out
    assert "/* TODO:" in out  # placeholders preserved
