"""Render description.ld / omni.ld stub / TOML reports."""

from io import StringIO

import tomli_w

from rom_analyzer.mode23_bindings import SpliceResolution
from rom_analyzer.types import (
    CrcRegion,
    FlashFreeBlock,
    PropagatedSymbol,
    RamFreeBlock,
)


def emit_description_ld(
    symbols: list[PropagatedSymbol],
    source_rom: str,
    reference_name: str,
    variant: str,
    match_summary: str,
) -> str:
    """Render a description.ld fragment."""
    by_cat: dict[str, list[PropagatedSymbol]] = {
        "data": [], "ram_global": [], "function": []
    }
    for s in symbols:
        by_cat[s.category].append(s)
    for k in by_cat:
        by_cat[k].sort(key=lambda s: s.new_address)

    out = StringIO()
    out.write(f"/* Generated by rom-analyzer from {source_rom}\n")
    out.write(f" * Reference: {reference_name}\n")
    out.write(f" * Variant:   {variant}\n")
    out.write(f" * Matched:   {match_summary}\n")
    out.write(" */\n\n")

    if by_cat["data"]:
        out.write("/* Flash table addresses */\n")
        for s in by_cat["data"]:
            out.write(f"{s.name} = 0x{s.new_address:x};\n")
        out.write("\n")

    if by_cat["ram_global"]:
        out.write("/* RAM globals */\n")
        for s in by_cat["ram_global"]:
            out.write(f"{s.name} = 0x{s.new_address:x};\n")
        out.write("\n")

    if by_cat["function"]:
        out.write("/* Function entry points */\n")
        for s in by_cat["function"]:
            out.write(f"{s.name} = 0x{s.new_address:x};\n")
        out.write("\n")

    return out.getvalue()


def emit_mode23_binding_line(name: str, res: SpliceResolution) -> str:
    """Render one splice-site binding for appending to description.ld.

    High confidence -> plain ld assignment.
    Otherwise       -> a /* VERIFY */ comment a human must confirm.
    """
    if res.confidence == "high" and res.address is not None:
        return f"{name} = 0x{res.address:x};\n"
    if res.address is not None:
        return (
            f"/* VERIFY: {name} = 0x{res.address:x}; "
            f"(low confidence — confirm in Ghidra) */\n"
        )
    return (
        f"/* VERIFY: {name} = <unresolved> "
        f"(no matching call site — locate manually) */\n"
    )


def emit_omni_stub(
    flash_blocks: list[FlashFreeBlock],
    propagated_ram: list[PropagatedSymbol],
) -> str:
    """Render an omni.ld.stub with auto-filled free_space when unambiguous."""
    unprotected = sorted(
        (b for b in flash_blocks if b.band == "unprotected"),
        key=lambda b: b.length,
        reverse=True,
    )
    out = StringIO()
    out.write("INCLUDE ../m32170.ld\n")
    out.write("INCLUDE ../math.ld\n")
    out.write("INCLUDE description.ld\n\n")

    if propagated_ram:
        out.write("/* RAM globals (auto-propagated from reference) */\n")
        ram_sorted = sorted(propagated_ram, key=lambda s: s.new_address)
        for s in ram_sorted:
            out.write(f"{s.name} = 0x{s.new_address:x};\n")
        out.write("\n")

    out.write("/* === BELOW: human-curated placeholders === */\n\n")
    out.write("/* Free space region (auto-filled when unambiguous) */\n")
    if len(unprotected) == 1 or (
        len(unprotected) >= 2 and unprotected[0].length > 2 * unprotected[1].length
    ):
        b = unprotected[0]
        out.write(f"free_space_start = 0x{b.start:x};\n")
        out.write(f"free_space_end   = 0x{b.end:x};\n")
    else:
        out.write("/* TODO: free_space_start = ???; */\n")
        out.write("/* TODO: free_space_end   = ???; */\n")
    out.write("\n")

    out.write("/* Per-ROM patch parameters (compare against mmc-patches/m32r/) */\n")
    out.write("/* TODO: post_fuel_cut_enrichment = ???; */\n\n")

    out.write("/* Call-site hook locations (extract from match-report.md) */\n")
    out.write("/* TODO: load400 bindings */\n")

    return out.getvalue()


def emit_crc_region_toml(region: CrcRegion) -> str:
    data = {
        "full_flash":    {"start": region.full_start,    "end": region.full_end},
        "partial_flash": {"start": region.partial_start, "end": region.partial_end},
    }
    return tomli_w.dumps(data)


def emit_flash_free_toml(blocks: list[FlashFreeBlock]) -> str:
    data = {"block": [
        {"band": b.band, "start": b.start, "end": b.end, "length": b.length}
        for b in blocks
    ]}
    return tomli_w.dumps(data)


def emit_ram_free_toml(blocks: list[RamFreeBlock]) -> str:
    data = {"block": [
        {"start": b.start, "end": b.end, "length": b.length, "note": b.note}
        for b in blocks
    ]}
    return tomli_w.dumps(data)


def emit_dtc_map_toml(dtc_entries: list) -> str:
    """Render dtc-map.toml: DTC (word, bit) → P-code + standard name + setter call sites."""
    rows = []
    for e in dtc_entries:
        row: dict = {
            "word": e.word,
            "bit": e.bit,
            "p_code": e.p_code_str,
        }
        if e.std_name:
            row["std_name"] = e.std_name
        if e.setters:
            row["setters"] = [
                {
                    "call_site": f"0x{s.call_site_addr:x}",
                    "caller": f"0x{s.caller_addr:x}",
                    "is_set": s.is_set,
                    **({"caller_name": s.caller_name} if s.caller_name else {}),
                }
                for s in e.setters
            ]
        rows.append(row)
    return tomli_w.dumps({"dtc": rows})


def emit_obd_pid_symbols(pid_entries: list) -> str:
    """Render OBD PID source RAM addresses as PROVIDE() lines for description.ld."""
    if not pid_entries:
        return ""
    out = StringIO()
    out.write("\n/* OBD PID source RAM addresses (auto-discovered by --emit-obd) */\n")
    for p in pid_entries:
        name = p.std_name or f"oem_mode{p.mode:02x}_pid_{p.pid:02x}_source"
        comment = f"  /* mode={p.mode:#x} pid={p.pid:#x} confidence={p.confidence} */"
        out.write(f"PROVIDE({name} = 0x{p.ram_addr:x});{comment}\n")
    return out.getvalue()
