"""Render description.ld / omni.ld stub / TOML reports."""

from io import StringIO

import tomli_w

from rom_analyzer.types import (
    CrcRegion,
    FlashFreeBlock,
    PropagatedSymbol,
    RamFreeBlock,
)


def emit_description_ld(
    symbols: list[PropagatedSymbol],
    source_rom: str,
    reference_name: str,
    variant: str,
    match_summary: str,
) -> str:
    """Render a description.ld fragment."""
    by_cat: dict[str, list[PropagatedSymbol]] = {
        "data": [], "ram_global": [], "function": []
    }
    for s in symbols:
        by_cat[s.category].append(s)
    for k in by_cat:
        by_cat[k].sort(key=lambda s: s.new_address)

    out = StringIO()
    out.write(f"/* Generated by rom-analyzer from {source_rom}\n")
    out.write(f" * Reference: {reference_name}\n")
    out.write(f" * Variant:   {variant}\n")
    out.write(f" * Matched:   {match_summary}\n")
    out.write(" */\n\n")

    if by_cat["data"]:
        out.write("/* Flash table addresses */\n")
        for s in by_cat["data"]:
            out.write(f"{s.name} = 0x{s.new_address:x};\n")
        out.write("\n")

    if by_cat["ram_global"]:
        out.write("/* RAM globals */\n")
        for s in by_cat["ram_global"]:
            out.write(f"{s.name} = 0x{s.new_address:x};\n")
        out.write("\n")

    if by_cat["function"]:
        out.write("/* Function entry points */\n")
        for s in by_cat["function"]:
            out.write(f"{s.name} = 0x{s.new_address:x};\n")
        out.write("\n")

    return out.getvalue()


def emit_omni_stub(
    flash_blocks: list[FlashFreeBlock],
    propagated_ram: list[PropagatedSymbol],
) -> str:
    """Render an omni.ld.stub with auto-filled free_space when unambiguous."""
    unprotected = sorted(
        (b for b in flash_blocks if b.band == "unprotected"),
        key=lambda b: b.length,
        reverse=True,
    )
    out = StringIO()
    out.write("INCLUDE ../m32170.ld\n")
    out.write("INCLUDE ../math.ld\n")
    out.write("INCLUDE description.ld\n\n")

    if propagated_ram:
        out.write("/* RAM globals (auto-propagated from reference) */\n")
        ram_sorted = sorted(propagated_ram, key=lambda s: s.new_address)
        for s in ram_sorted:
            out.write(f"{s.name} = 0x{s.new_address:x};\n")
        out.write("\n")

    out.write("/* === BELOW: human-curated placeholders === */\n\n")
    out.write("/* Free space region (auto-filled when unambiguous) */\n")
    if len(unprotected) == 1 or (
        len(unprotected) >= 2 and unprotected[0].length > 2 * unprotected[1].length
    ):
        b = unprotected[0]
        out.write(f"free_space_start = 0x{b.start:x};\n")
        out.write(f"free_space_end   = 0x{b.end:x};\n")
    else:
        out.write("/* TODO: free_space_start = ???; */\n")
        out.write("/* TODO: free_space_end   = ???; */\n")
    out.write("\n")

    out.write("/* Per-ROM patch parameters (compare against mmc-patches/m32r/) */\n")
    out.write("/* TODO: post_fuel_cut_enrichment = ???; */\n\n")

    out.write("/* Call-site hook locations (extract from match-report.md) */\n")
    out.write("/* TODO: load400 bindings */\n")

    return out.getvalue()


def emit_crc_region_toml(region: CrcRegion) -> str:
    data = {
        "full_flash":    {"start": region.full_start,    "end": region.full_end},
        "partial_flash": {"start": region.partial_start, "end": region.partial_end},
    }
    return tomli_w.dumps(data)


def emit_flash_free_toml(blocks: list[FlashFreeBlock]) -> str:
    data = {"block": [
        {"band": b.band, "start": b.start, "end": b.end, "length": b.length}
        for b in blocks
    ]}
    return tomli_w.dumps(data)


def emit_ram_free_toml(blocks: list[RamFreeBlock]) -> str:
    data = {"block": [
        {"start": b.start, "end": b.end, "length": b.length, "note": b.note}
        for b in blocks
    ]}
    return tomli_w.dumps(data)
