"""SAE J1979 Mode 01 PID standard names and SAE J2012 DTC standard descriptions."""

# Keys: (mode, pid_byte). Mode 01 = live data, Mode 02 = freeze frame.
STD_PIDS: dict[tuple[int, int], str] = {
    (1, 0x00): "supported_pids_01_20",
    (1, 0x01): "dtc_count_and_mil_status",
    (1, 0x02): "freeze_frame_dtc",
    (1, 0x03): "fuel_system_status",
    (1, 0x04): "calculated_engine_load",
    (1, 0x05): "coolant_temp_c",
    (1, 0x06): "stft_bank1",
    (1, 0x07): "ltft_bank1",
    (1, 0x08): "stft_bank2",
    (1, 0x09): "ltft_bank2",
    (1, 0x0A): "fuel_pressure_kpa",
    (1, 0x0B): "map_pressure_kpa",
    (1, 0x0C): "engine_rpm",
    (1, 0x0D): "vehicle_speed_kmh",
    (1, 0x0E): "ignition_timing_advance_deg",
    (1, 0x0F): "intake_air_temp_c",
    (1, 0x10): "maf_air_flow_rate_g_s",
    (1, 0x11): "throttle_position_pct",
    (1, 0x12): "commanded_secondary_air_status",
    (1, 0x13): "oxygen_sensors_present_2banks",
    (1, 0x14): "o2_b1s1_voltage",
    (1, 0x15): "o2_b1s2_voltage",
    (1, 0x16): "o2_b1s3_voltage",
    (1, 0x17): "o2_b1s4_voltage",
    (1, 0x18): "o2_b2s1_voltage",
    (1, 0x19): "o2_b2s2_voltage",
    (1, 0x1A): "o2_b2s3_voltage",
    (1, 0x1B): "o2_b2s4_voltage",
    (1, 0x1C): "obd_standards_compliance",
    (1, 0x1D): "oxygen_sensors_present_4banks",
    (1, 0x1E): "aux_input_status",
    (1, 0x1F): "runtime_since_engine_start_s",
    (1, 0x20): "supported_pids_21_40",
    (1, 0x21): "distance_with_mil_on_km",
    (1, 0x22): "fuel_rail_pressure_kpa",
    (1, 0x23): "fuel_rail_gauge_pressure_kpa",
    (1, 0x24): "o2_b1s1_equiv_ratio_voltage",
    (1, 0x25): "o2_b1s2_equiv_ratio_voltage",
    (1, 0x2C): "commanded_egr_pct",
    (1, 0x2D): "egr_error_pct",
    (1, 0x2E): "commanded_evap_purge_pct",
    (1, 0x2F): "fuel_tank_level_pct",
    (1, 0x30): "warmups_since_dtcs_cleared",
    (1, 0x31): "distance_since_dtcs_cleared_km",
    (1, 0x32): "evap_sys_vapor_pressure_pa",
    (1, 0x33): "abs_barometric_pressure_kpa",
    (1, 0x42): "control_module_voltage_v",
    (1, 0x43): "absolute_load_pct",
    (1, 0x44): "commanded_equiv_ratio",
    (1, 0x45): "relative_throttle_pos_pct",
    (1, 0x46): "ambient_air_temp_c",
    (1, 0x47): "abs_throttle_pos_b_pct",
    (1, 0x49): "accelerator_pedal_pos_d_pct",
    (1, 0x4A): "accelerator_pedal_pos_e_pct",
    (1, 0x4C): "commanded_throttle_actuator_pct",
    # Mode 02 = freeze frame; PID 0x02 identifies the triggering DTC
    (2, 0x02): "freeze_frame_dtc",
}

# Keys: decimal integer of the P-code digits (e.g. P0100 → 100).
STD_DTC_NAMES: dict[int, str] = {
    # P01xx — Fuel and air metering
    100: "maf_circuit_malfunction",
    101: "maf_circuit_range_performance",
    102: "maf_circuit_low_input",
    103: "maf_circuit_high_input",
    105: "map_circuit_malfunction",
    106: "map_circuit_range_performance",
    107: "map_circuit_low_input",
    108: "map_circuit_high_input",
    110: "iat_circuit_malfunction",
    111: "iat_circuit_range_performance",
    112: "iat_circuit_low_input",
    113: "iat_circuit_high_input",
    115: "ect_circuit_malfunction",
    116: "ect_circuit_range_performance",
    117: "ect_circuit_low_input",
    118: "ect_circuit_high_input",
    120: "tps_circuit_malfunction",
    121: "tps_circuit_range_performance",
    122: "tps_circuit_low_input",
    123: "tps_circuit_high_input",
    125: "insufficient_coolant_temp_fuel_control",
    128: "map_performance_abnormal",
    130: "o2_circuit_malfunction_b1s1",
    131: "o2_circuit_range_b1s1",
    132: "o2_circuit_low_voltage_b1s1",
    133: "o2_circuit_slow_response_b1s1",
    134: "o2_circuit_no_activity_b1s1",
    135: "o2_heater_circuit_b1s1",
    136: "o2_circuit_malfunction_b1s2",
    137: "o2_circuit_low_voltage_b1s2",
    138: "o2_circuit_high_voltage_b1s2",
    139: "o2_circuit_slow_response_b1s2",
    141: "fuel_system_lean_b1",
    170: "fuel_system_lean_overall",
    171: "fuel_system_lean_b1",
    172: "fuel_system_rich_b1",
    173: "fuel_system_lean_b2",
    174: "fuel_system_rich_b2",
    # P02xx — Fuel and air metering (injectors)
    200: "fuel_injector_circuit_malfunction",
    201: "injector_circuit_malfunction_cyl1",
    202: "injector_circuit_malfunction_cyl2",
    203: "injector_circuit_malfunction_cyl3",
    204: "injector_circuit_malfunction_cyl4",
    # P03xx — Ignition and misfire
    300: "random_multiple_cylinder_misfire",
    301: "misfire_cylinder1",
    302: "misfire_cylinder2",
    303: "misfire_cylinder3",
    304: "misfire_cylinder4",
    325: "knock_sensor_circuit_malfunction_b1",
    326: "knock_sensor_circuit_range_b1",
    327: "knock_sensor_circuit_low_b1",
    328: "knock_sensor_circuit_high_b1",
    335: "crank_position_sensor_malfunction",
    336: "crank_position_sensor_range",
    340: "cam_position_sensor_malfunction",
    341: "cam_position_sensor_range",
    # P04xx — Emission controls
    400: "egr_flow_malfunction",
    401: "egr_flow_insufficient",
    402: "egr_flow_excessive",
    403: "egr_solenoid_malfunction",
    404: "egr_open_pos_sensor_range",
    405: "egr_open_pos_sensor_low",
    406: "egr_open_pos_sensor_high",
    410: "secondary_air_injection_malfunction",
    411: "secondary_air_injection_flow",
    420: "catalyst_efficiency_below_threshold_b1",
    421: "main_catalyst_efficiency_below_threshold_b1",
    430: "catalyst_efficiency_below_threshold_b2",
    440: "evap_emission_control_malfunction",
    441: "evap_emission_control_incorrect_purge",
    442: "evap_emission_control_small_leak",
    443: "evap_emission_control_purge_solenoid",
    446: "evap_emission_control_vent_solenoid",
    450: "evap_emission_control_system_large_leak",
    455: "evap_emission_control_leak_detected",
    460: "fuel_level_sensor_malfunction",
    461: "fuel_level_sensor_range",
    462: "fuel_level_sensor_low",
    463: "fuel_level_sensor_high",
    # P05xx — Vehicle speed, idle control
    500: "vehicle_speed_sensor_malfunction",
    505: "idle_control_system_malfunction",
    506: "idle_control_system_rpm_low",
    507: "idle_control_system_rpm_high",
    # P06xx — Computer and output circuits
    600: "serial_communication_link_malfunction",
}
